##############################
#
# Open ELM/CLM R arrays and plot 
#
# AWalker
# May 2021 (update Aug 2022)
# BSharma
# Mar 2022
##############################

rm(list=ls())

# data processing
library(dplyr)
library(tidyr)
library(stringr)

# plotting
library(lattice)
library(grid)
library(viridisLite)
library(viridis)


# load functions etc
wd_src <- '/Volumes/disk2/Research_Projects/FATES/runs/FACE/FATESFACE_analysis'
wd_src <- '/Users/ud4/repos/GitHub/FATESFACE' # bs
setwd(wd_src)

# 'load_obs.R' expects observed data to be on hard-drive, open that script first and customize to your setup
# data can be found on ESS-DIVE, FACE-MDS Phase 2 Experiment data
source('load_obs.R')



# Initialise
############################

# paths
root    <- '/Volumes/disk2/Research_Projects/FATES/runs/FACE/'
root    <- '/Users/ud4/FATESMDS_analysis/outputs/runs/tests_alp' #bs
moddate <- '230309' #'221205'
wdo     <-paste(root, moddate, "plots", sep = "/")
if(!file.exists(wdo)) dir.create(wdo)


# filename variables
# single runs
#caseidprefix_gen <- 'Bharat_AW_logfix_api25e3sm_mf0df100_r0301' # MF=0 Log
#caseidprefix_gen <- 'Bharat_AW_logfix_api25e3sm_mf1df100_r0303' # MF=1 Log
#caseidprefix_gen <- 'Bharat_AW_NoLogging_api25e3sm_r0303b' # MF=1 NoLog
caseidprefix_gen <- 'Bharat_AW_NoLogging_api25e3sm_r0301b' # MF=0 NoLog

caseidprefix_var <- c('C', 'CNP_ECA', 'CNP_RD' )
caseidprefix_var <- c('', 'ECA', 'RD' ) #bs
caseidprefix <- paste(caseidprefix_gen,caseidprefix_var,sep='_')
caseidprefix[1] = caseidprefix_gen  # BS: since the Conly is same as the original file name

# Logging and mort_disturb_frac ? 
MF = 0 # [0 1]
Logging = "NoLog" # "Log" or "NoLog" 

sites        <- c('US-DUK', 'US-ORN' )
cases        <- c('aCO2', 'eCO2' )
years        <- list(
  `US-DUK` = 1996:2007,
  `US-ORN` = 1998:2008
) 


# calculate additional variables from model output 
add_vars     <- T

# calculate additional variables from observations 
add_vars_obs <- T

# plotting settings - yet to be added into plotlist
# also figure out how to insert variables into expressions
colrs      <- rep(c(viridis(10)[3],viridis(10)[7]), each=2 ) 
case_colrs <- viridis 
ltypes     <- 1 
lalpha     <- c(0.5,1) 
leg_cols   <- 2

# open RDS lists of arrays - these need to have been generated by ELM_postprocessR
#############################################
# moved from top lines of Anthony's code
source(paste0(wd_src,'/functions_FATESFACE_fatesoutv2.R'))
source(paste0(wd_src,'/lists_plotting_FATESFACE_fatesoutv2.R')) 

# create a 3-level list of caseidprefix (level 1), site (level 2), & co2 (level 3)
l1 <- list()
# Tips:> It will be a good idea to include other scenarios in the caseidprefix i.e. Logging!xMF!
for(c in caseidprefix) {
  #setwd(paste(root,moddate,caseidprefix_gen,sep='/')) #bs
  #Creating a parent dir in which the plots will be saved for C/CNP
  #dir.create(file.path(root,moddate,caseidprefix_gen), showWarnings = FALSE)
  setwd(file.path(root,moddate,paste0(c,'_processed'))) 
  
  #setwd(paste0(c,'_processed'))
  print('')
  print(getwd())

  l2 <- list()
  for(s in sites) {
    l3 <- list()
    for(co2 in cases) {

      # read annual data and extract lndgrd,time array
      fname <- paste(c,s,co2,'annual',sep='_')
      print(fname)
      rl1   <- readRDS(paste0(fname,'.RDS'))
      a1    <- rl1$data_arrays$`lndgrid,time`
      # currently not added to any data structure
      a2    <- rl1$data_arrays$`lndgrid,fates_levscls,time`
      a3    <- rl1$data_arrays$`lndgrid,levgrnd,time`

      # add variables
      if(add_vars) {
        a1 <- add_vars_lndtime(a1, add_vars_list )
        if(grepl('ECA',c)) a1 <- add_vars_lndtime(a1, add_vars_list_cnp )
        if(grepl('RD',c)) a1 <- add_vars_lndtime(a1, add_vars_list_cnp )
      } 

      # combine data
      l3    <- c(l3,list(a1))
      names(l3)[length(l3)] <- co2
    }
    l2    <- c(l2,list(l3))
    names(l2)[length(l2)] <- s
  }
  l1    <- c(l1,list(l2))
  names(l1)[length(l1)] <- c
}


format(object.size(l1),units='Mb')
names(l1)
names(l1[[1]])
names(l1[[1]][[1]])
class(l1[[1]][[1]][[1]])
class(l1[[1]][[1]][[1]])
# head(l1[[1]][[1]][[1]])

rl1$data_arrays[["lndgrid,time"]]
names(rl1$data_arrays)

# names(rl1)
# rl1$dimensions
# rl1$dim_combinations
# names(rl1$variables)
rl1$variables
rl1$variables['TLAI']
names(rl1$data_arrays)
dimnames(rl1$data_arrays$`lndgrid,time`)
# rl1$data_arrays
class(rl1$data_arrays)
lapply(rl1$data_arrays, class )
lapply(rl1$data_arrays, dim )
lapply(rl1$data_arrays, dimnames )


# The following comment block is an attempt in progress to make a function for calculations, shown above.

# extract ELM/FATES data from RDS 
# -- create a 3-level list of caseidprefix (level 1), site (level 2), & case/co2 (level 3)
# extract_model_data <- function(
#     wd=paste(root,moddate,caseidprefix_gen,sep='/'),
#     caseidprefix=c("FACE_api25_C", "FACE_api25_CNP_ECA", "FACE_api25_CNP_RD" ),
#     sites=c('US-DUK', 'US-ORN' ),
#     cases=c('aCO2', 'eCO2' ),
#     array_ex=c( lndtime='lndgrid,time' ) 
#     
#     ) {
#   
#   l1 <- list()
#   for(cidp in caseidprefix) {
#     setwd(wd)
#     setwd(paste0(c,'_processed'))
#     print('')
#     print(getwd())
#     
#     l2 <- list()
#     for(s in sites) {
#       l3 <- list()
#       for(c in cases) {
#         
#         # read annual data and extract lndgrd,time array
#         fname <- paste(cidp,s,c,'annual',sep='_')
#         print(fname)
#         rl1   <- readRDS(paste0(fname,'.RDS'))
#         
#         # extract data frames
#         # - for/lapply
#         a1    <- rl1$data_arrays[[array_ex]]
#         # a1    <- rl1$data_arrays$`lndgrid,time`
#         # # currently not added to any data structure
#         # a2    <- rl1$data_arrays$`lndgrid,fates_levscls,time`
#         # a3    <- rl1$data_arrays$`lndgrid,levgrnd,time`
#         
#         # add variables
#         # - can make this more flexible
#         if(add_vars) {
#           # a1 <- add_vars_lndtime(a1, add_vars_list )
#           a1 <- get(paste('add_vars',names(array_ex),sep='_'))(a1, add_vars_list )
#           if(grepl('CNP',c)) a1 <- add_vars_lndtime(a1, add_vars_list_cnp )
#         } 
#         
#         # combine data
#         l3    <- c(l3,list(a1))
#         names(l3)[length(l3)] <- c
#       }
#       l2    <- c(l2,list(l3))
#       names(l2)[length(l2)] <- s
#     }
#     l1    <- c(l1,list(l2))
#     names(l1)[length(l1)] <- cidp
#   }
#}



lp <- calc_plot_vectors(l1, 'FATES_NPP', caseidprefix, sites, years )
names(lp)
plot_co2response_sites(lp, colrs=rep(c('blue','red'),each=2), ltypes=c(2,1), leg_cols=2,
                       ylab=expression("NPP [gC " * m^-2 * " y"^-1 * "]"))  

plot_co2response_sites(lp, colrs=viridis, leg_cols=2, inpanel='caseid',
                       ylab=expression("NPP [gC " * m^-2 * " y"^-1 * "]"))  

lp_resp <- calc_responseplot_vectors(l1, 'FATES_NPP', caseidprefix, sites, years, func='percent_array' )
plot_co2response_sites(lp_resp, inpanel='caseid',
                       colrs=viridis,
                       ltypes=1,
                       leg_cols=3,
                       ylab=expression("NPP [gC " * m^-2 * " y"^-1 * "]"))
   
pnpp <-
  plot_modobs(l1, df_obs, df_obsse, labs=var_labs$npp, fsite='DUKE', fco2='AMB',
            sites=sites, years=years, caseidprefix=caseidprefix, 
            MF = as.character(MF), Logging=as.character(Logging) )
pnpp[[1]]
pnpp[[2]]
pnpp[[3]]
pnpp[[4]]

labs <- list(
  FATES_NPP = list(
    fvar_obs = 'NPP',
    fvar_mod = 'FATES_NPP',
    base     = expression("NPP [gC " * m^-2 * " y"^-1 * "]"),
    resp     = expression("NPP response [gC " * m^-2 * " y"^-1 * "]"),
    rel      = expression("NPP response [%]"),
    ylim     = NULL, # c(0,1900),
    ylim_abs = NULL, #c(0,500),
    ylim_rel = NULL #c(0,50)
  ),
  
  NUP = list(
    base     = expression("N Uptake [gN " * m^-2 * " y"^-1 * "]"),
    resp     = expression("N Uptake response [gN " * m^-2 * " y"^-1 * "]"),
    rel      = expression("N Uptake response [%]"),
    ylim     = NULL, #c(0,12),
    ylim_abs = NULL, #c(-1,4),
    ylim_rel = NULL #c(-40,50)
  ),
  
  FROOT_alloc_frac = list(
    base     = expression("Fine Root alloc. frac. [-]"),
    resp     = expression("Fine Root alloc. frac. response [-]"),
    rel      = expression("Fine Root alloc. frac. response [%]"),
    ylim     = NULL,# c(0,0.6),
    ylim_abs = NULL,#c(-0.15,0.2),
    ylim_rel = NULL#c(-60,130)
  ),
  
  LEAF_FROOT_ratio = list(
    base     = expression("Leaf:Fine Root mass [-]"),
    resp     = expression("Leaf:Fine Root mass response [-]"),
    rel      = expression("Leaf:Fine Root mass response [%]"),
    ylim     = NULL, #c(0.25,7),
    ylim_abs = NULL,#c(-5,3),
    ylim_rel = NULL#c(-100,60)
  )
)



setwd(paste(root,moddate,sep='/'))
if(!file.exists('figures')) dir.create('figures') 
setwd('figures')
# plot_vars <- c('FATES_NPP', 'NUP', 'FROOT_alloc_frac', 'LEAF_FROOT_ratio' )
# plot_vars <- c('FATES_NPP')
width     <- 6 
height    <- 4 

names(var_labs)

# Plotting
co2_exp = 'AMB' # 'AMB', 'ELE' choose either

# Create a dir for every log, CO2 exp and mort distrub case
figure_save_path = file.path(root,moddate,'figures',paste0(Logging,'_MF',MF,'_',co2_exp))
dir.create(figure_save_path)

for(v in var_labs) {
  # i <- 1
  # for(c in caseidprefix_var_ens) {
  #   print(c)
  for(s in c('DUKE', 'ORNL' )) {
      print(s)
      
      # plot_data <- plot_ensemble_2d(pvar=v, fsite=s, case=c, plot_obs_regression=T, plotsetup=labs  )
      plot_data <- 
        plot_modobs(l1, df_obs, df_obsse, labs=v, fvar=NULL, fsite=s, fco2=co2_exp,
                    sites=sites, years=years, caseidprefix=caseidprefix, 
                    MF = as.character(MF), Logging=as.character(Logging))

      plot_list <- if(s=='DUKE') list(plot_data) else  c(plot_list, list(plot_data) )
      
    }
  
  
  # print plots
  #pdf(paste0(v$fvar_mod,'.pdf'), width=2*width, height=4*height )
  pdf( paste0(figure_save_path,'/',v$fvar_mod,'.pdf'), 
      width=2*width, height=4*height )
  
  
  p <- 1
  print(plot_list[[1]][[p]], split=c(1,1,2,4), more=T )
  print(plot_list[[2]][[p]], split=c(2,1,2,4), more=T )

  p <- 2
  print(plot_list[[1]][[p]], split=c(1,2,2,4), more=T )
  print(plot_list[[2]][[p]], split=c(2,2,2,4), more=T )
  
  p <- 3
  print(plot_list[[1]][[p]], split=c(1,3,2,4), more=T )
  print(plot_list[[2]][[p]], split=c(2,3,2,4), more=T )
  
  p <- 4
  print(plot_list[[1]][[p]], split=c(1,4,2,4), more=T )
  print(plot_list[[2]][[p]], split=c(2,4,2,4), more=T )

  dev.off()
  
}



#dimnames(`a2_ECA_US-DUK_aCO2`)

df_obs$CO2.real[df_obs$co2=='ELE']/
  df_obs$CO2.real[df_obs$co2=='AMB']

df_obs$CO2.real[df_obs$site=='ORNL'&df_obs$co2=='ELE']
mean(df_obs$CO2.real[df_obs$site=='ORNL'&df_obs$co2=='ELE'])
mean(df_obs$CO2.real[df_obs$site=='ORNL'&df_obs$co2=='AMB'])

df_obs$GR[df_obs$site=='ORNL'&df_obs$co2=='AMB']
df_obs$CFR[df_obs$site=='ORNL'&df_obs$co2=='AMB']


names(df_obs)


xyplot(CO2.real~YEAR|site, df_obs, groups=co2 )
xyplot(GR~YEAR|site, df_obs, groups=co2 )
xyplot(CFR~YEAR|site, df_obs, groups=co2 )


xyplot(1:10~1:10, key=list(x=0,y=1,corner=c(0,1),text=list('ORNL ECA')))




###############################################
# Load structure ensemble

wdo_ens_struct <- paste(root,moddate_ens_struct,'plots',sep='/')  

setwd(paste(root,moddate_ens_struct,caseidprefix_gen_ens_struct,sep='/'))
setwd(ensemble)
list.files()
ens_file <- 'FACE_ensembleCNP_RD_US-ORN_spins_UQconcatenated.RDS'
l2 <- readRDS(ens_file)
names(l2)
parl_file <- 'structure1_parm_list'
parv_file <- 'structure1_parm_vals'
df1       <- read.table(parl_file, header=F ) 
df2       <- read.table(parv_file, header=F ) 
df1
df2
names(df1) <- c('parname', 'PFTnumber', 'min', 'max' )
names(df2) <- df1[,1]
l2$ensemble_par_list <- tibble(df1)
l2$ensemble_par_vals <- tibble(df2)

names(l2$data_arrays)
names(l2$data_arrays)[19]
dimcomb <- names(l2$data_arrays)[19]
a1    <- l2$data_arrays[[dimcomb]]
dim(a1)
dimnames(a1)
dimcomb <- names(l2$data_arrays)[18]
a2    <- l2$data_arrays[[dimcomb]]
dim(a2)
dimnames(a2)

p1 <- 
  xyplot(a2[,,'TLAI',]~rep(1:dim(a2)[2],dim(a2)[4]), groups=rep(1:dim(a2)[3],each=dim(a2)[2]),
         xlab='year', ylab='LAI',
         type='l'  )

pdf('TLAI.pdf', 6, 5 )
print(p1)
dev.off()


# create LAI_SCLS variable
a1[,,,'DDBH_CANOPY_SCLS',] <- 
  a1[,,,'LAI_CANOPY_SCLS',] +
  a1[,,,'LAI_UNDERSTORY_SCLS',]
dimnames(a1)$vars[3] <- 'LAI_SCLS'

# ensemble par vals
names(l2$ensemble_par_vals)
tibble(l2$ensemble_par_vals) 


a1   <- a1
vid  <- 2
na0  <- T 
log  <- F
pa2sub    <- NULL
var2      <- l2$dim_variables$fates_levscls$vals
var_deets <- l2$variables[[dimnames(a1)$vars[vid]]]
fates_dim <- names(dimnames(a1)[2])


dimnames(a1)$vars
which(dimnames(a1)$vars == paste0('LAI','_SCLS'))

plots <- plot3d_ensemble(a1, 3, var_label="LAI by size class [m2/m2]", zmax=9 )
plots[[1]]
plots[[2]]
plots[[4]]
plots[[3]]


setwd(wdo_ens_struct)
vars_lab   <- c('AGB', 'LAI', 'LAI_CANOPY', 'LAI_UNDERSTORY', 'BA', 'NPLANT' )
zmaxs      <- c(NA, 9, 9, 9, NA, NA )
var_labels <- c(NA, "LAI by size class [m2/m2]", "Canopy LAI by size class [m2/m2]", "Understory LAI by size class [m2/m2]", NA, NA )
for(v1 in 1:length(vars_lab)) {

  var1 <- vars_lab[v1]
  print(var1)
  
  logt <- F
  if(var1%in%c('NPLANT')) logt <- T
  plots <- plot3d_ensemble(a1, which(dimnames(a1)$vars == paste0(var1,'_SCLS')), logt=logt, var_label=var_labels[v1], zmax=zmaxs[v1] )
  
  pdf(paste0('Size_class_',var1,'.pdf'), 14, 10)
  print(plots[[1]])
  dev.off()

  pdf(paste0('Size_class_',var1,'_2d.pdf'), 6, 5 )
  print(update(plots[[3]], legend=NULL ))
  dev.off()
}


tibble(l2$ensemble_par_vals) 
names(l2$ensemble_par_vals)







# # met data
# # for PI meeting poster
# ##################################
# 
# 
# setwd(paste0(root,moddate,'/plots'))
# # pdf('NPP_reponse_Duke.pdf', width=6.5, height=3.5 )
# # plot_response(lp_resp, subset(dfo_npp_co2, site=='DUKE'), site='US-DUK' )
# # dev.off()
# 
# # pdf('NPP_reponse_ORNL.pdf', width=6.5, height=3.5 )
# # plot_response(lp_resp, subset(dfo_npp_co2, site=='ORNL'), site='US-ORN' )
# # dev.off()
# 
# data_func = 'calc_responseplot_vectors'
# resp_func = 'percent_array'
# plot_func = 'plot_co2response_sites'
# var  = 'GPP'
# ylab = expression("GPP response [%]")
# 
# lp <- calc_plot_vectors(l1, 'NPP', caseidprefix, sites, years )
# plot_co2response_sites(lp, colrs=rep(c('blue','red'),each=2), ltypes=c(1,2), leg_cols=2,
#                        ylab=expression("NPP [gC " * m^-2 * " y"^-1 * "]"))  
# 
# colrs <- magma(3)
# xyplot(l1[] ~ lp$vx | lp[[outpanel]], groups=lp[[inpanel]],
#        type='l', scales=list(tck=c(-0.5,-0.5), alternating=F ), as.table=T,
#        xlab='Year',
#        par.settings=simpleTheme(col=colrs, lwd=2, lty=ltypes ), 
#        strip=strip.custom(bg='grey90',par.strip.text=list(cex=0.75)),
#        auto.key=list(lines=T, points=F, corner=c(0,0), x=0, y=1, columns=leg_cols,
#                      border=T, cex=0.75, background='white'))
# 
# 
# sitecolrs <- c('blue','red')
# 
# lp_rain <- calc_plot_vectors2(l1, 'RAIN', caseidprefix[1], sites, years )
# pr <- 
#   xyplot(lp_rain$vy ~ lp_rain$vx, groups=lp_rain$sites,
#          type='l', scales=list(tck=c(-0.5,-0.5), alternating=F, x=list(at=seq(1996,2008,4)) ),
#          xlab='Year', ylab=expression('Precipitation [mm '*y^-1*']'),
#          par.settings=simpleTheme(col=sitecolrs, lwd=2, lty=1 )#, 
#          # auto.key=list(lines=T, points=F, corner=c(0,0), x=0, y=1, columns=1,
#          #               border=T, cex=0.75, background='white')
#   )
# pr
# 
# lp_temp <- calc_plot_vectors2(l1, 'TBOT', caseidprefix[1], sites, years )
# pt <- 
#   xyplot(lp_temp$vy ~ lp_temp$vx, groups=lp_temp$sites,
#          type='l', scales=list(tck=c(-0.5,-0.5), alternating=F, x=list(at=seq(1996,2008,4)) ),
#          xlab='Year', ylab=expression('Air Temperature ['*degree*'C]'),
#          par.settings=simpleTheme(col=sitecolrs, lwd=2, lty=1 ),
#          auto.key=list(lines=T, points=F, corner=c(0,0), x=0, y=1, columns=1,
#                        border=T, cex=0.75, background='white')
#   )
# pt 
# 
# lp_swrad <- calc_plot_vectors2(l1, 'FSDS', caseidprefix[1], sites, years )
# psw <- 
#   xyplot(lp_swrad$vy ~ lp_swrad$vx, groups=lp_swrad$sites,
#          type='l', scales=list(tck=c(-0.5,-0.5), alternating=F, x=list(at=seq(1996,2008,4)) ),
#          xlab='Year', ylab=expression('SW Radiation ['*W*m^-2*']'),
#          par.settings=simpleTheme(col=sitecolrs, lwd=2, lty=1 )#, 
#          # auto.key=list(lines=T, points=F, corner=c(0,0), x=0, y=1, columns=1,
#          #               border=T, cex=0.75, background='white')
#   )
# psw
# 
# setwd(paste0(root,moddate,'/plots'))
# pdf('met_data.pdf', width=10, height=3.5 )
# print(pt, split=c(1,1,3,1), more=T )
# print(pr, split=c(2,1,3,1), more=T )
# print(psw, split=c(3,1,3,1), more=F )
# dev.off()
# 
# 



### END ###